"""initial schema

Revision ID: 32eb1398b34b
Revises: 
Create Date: 2026-09-12 18:30:38.709757+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '32eb1398b34b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_table('assets',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_class', sa.Enum('EQUITY', 'ETF', 'CRYPTO', 'FOREX', 'FUTURE', 'OPTION', 'COMMODITY', name='assetclass', native_enum=False), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_sector'), 'assets', ['sector'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('market_candles',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_candles')),
    sa.UniqueConstraint('symbol', 'timeframe', 'candle_time', name='uq_market_candles_symbol_tf_time')
    )
    op.create_index(op.f('ix_market_candles_candle_time'), 'market_candles', ['candle_time'], unique=False)
    op.create_index(op.f('ix_market_candles_created_at'), 'market_candles', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_candles_symbol'), 'market_candles', ['symbol'], unique=False)
    op.create_table('market_quotes',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('bid', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('ask', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('last', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('quote_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_quotes'))
    )
    op.create_index(op.f('ix_market_quotes_created_at'), 'market_quotes', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_quotes_quote_time'), 'market_quotes', ['quote_time'], unique=False)
    op.create_index(op.f('ix_market_quotes_symbol'), 'market_quotes', ['symbol'], unique=False)
    op.create_index('ix_market_quotes_symbol_quote_time', 'market_quotes', ['symbol', 'quote_time'], unique=False)
    op.create_table('strategies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('strategy_type', sa.Enum('TREND_FOLLOWING', 'MOMENTUM', 'MEAN_REVERSION', 'CUSTOM', name='strategytype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('asset_classes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    op.create_index(op.f('ix_strategies_created_at'), 'strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategies_slug'), 'strategies', ['slug'], unique=True)
    op.create_table('system_events',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_correlation_id'), 'system_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_occurred_at'), 'system_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_system_events_source'), 'system_events', ['source'], unique=False)
    op.create_index('ix_system_events_type_occurred', 'system_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('backtests',
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus', native_enum=False), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtests_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    op.create_index(op.f('ix_backtests_created_at'), 'backtests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_table('broker_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('broker', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='brokermode', native_enum=False), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_accounts'))
    )
    op.create_index(op.f('ix_broker_accounts_created_at'), 'broker_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_broker_accounts_external_account_id'), 'broker_accounts', ['external_account_id'], unique=False)
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity', native_enum=False), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='signaldirection', native_enum=False), nullable=False),
    sa.Column('strength', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('time_horizon', sa.Enum('INTRADAY', 'SWING', 'POSITION', 'LONG_TERM', name='timehorizon', native_enum=False), nullable=True),
    sa.Column('indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_signals_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_signals'))
    )
    op.create_index(op.f('ix_strategy_signals_created_at'), 'strategy_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_time'), 'strategy_signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_strategy_signals_strategy_id'), 'strategy_signals', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_signals_symbol'), 'strategy_signals', ['symbol'], unique=False)
    op.create_index('ix_strategy_signals_symbol_signal_time', 'strategy_signals', ['symbol', 'signal_time'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_jti', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_name')
    )
    op.create_index(op.f('ix_watchlists_created_at'), 'watchlists', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('backtest_id', sa.Uuid(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('final_capital', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('average_win', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('average_loss', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('exposure_pct', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('equity_curve', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('trade_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_backtest_results_backtest_id_backtests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_results'))
    )
    op.create_index(op.f('ix_backtest_results_backtest_id'), 'backtest_results', ['backtest_id'], unique=True)
    op.create_index(op.f('ix_backtest_results_created_at'), 'backtest_results', ['created_at'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('broker_account_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('cash', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_portfolios_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_index(op.f('ix_portfolios_broker_account_id'), 'portfolios', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_portfolios_created_at'), 'portfolios', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_watchlist_items_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_items_watchlist_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_asset_id'), 'watchlist_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_created_at'), 'watchlist_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlist_items_symbol'), 'watchlist_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('invested', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('daily_return_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('exposure_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('positions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_created_at'), 'portfolio_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_snapshots_portfolio_time', 'portfolio_snapshots', ['portfolio_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_time'), 'portfolio_snapshots', ['snapshot_time'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('SAFE', 'WARNING', 'CRITICAL', name='risklevel', native_enum=False), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('exposure_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_risk_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_snapshots'))
    )
    op.create_index(op.f('ix_risk_snapshots_created_at'), 'risk_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_portfolio_id'), 'risk_snapshots', ['portfolio_id'], unique=False)
    op.create_index('ix_risk_snapshots_portfolio_time', 'risk_snapshots', ['portfolio_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_snapshot_time'), 'risk_snapshots', ['snapshot_time'], unique=False)
    op.create_table('trade_proposals',
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY', 'ETF', 'CRYPTO', 'FOREX', 'FUTURE', 'OPTION', 'COMMODITY', name='assetclass', native_enum=False), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', 'CLOSE', 'REDUCE', name='orderaction', native_enum=False), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED', 'CANCELLED', name='proposalstatus', native_enum=False), nullable=False),
    sa.Column('proposed_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('proposed_position_percentage', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('time_horizon', sa.Enum('INTRADAY', 'SWING', 'POSITION', 'LONG_TERM', name='timehorizon', native_enum=False), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('market_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('market_regime', sa.Enum('BULLISH', 'BEARISH', 'SIDEWAYS', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', name='marketregime', native_enum=False), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_trade_proposals_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_trade_proposals_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trade_proposals_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_proposals'))
    )
    op.create_index(op.f('ix_trade_proposals_agent_run_id'), 'trade_proposals', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_created_at'), 'trade_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_proposals_portfolio_id'), 'trade_proposals', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_status'), 'trade_proposals', ['status'], unique=False)
    op.create_index('ix_trade_proposals_status_created', 'trade_proposals', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_trade_proposals_strategy_id'), 'trade_proposals', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_symbol'), 'trade_proposals', ['symbol'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', 'CLOSE', 'REDUCE', name='orderaction', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('market_regime', sa.Enum('BULLISH', 'BEARISH', 'SIDEWAYS', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', name='marketregime', native_enum=False), nullable=True),
    sa.Column('strategy_signal_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_decisions_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_agent_decisions_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_agent_decisions_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_decisions'))
    )
    op.create_index(op.f('ix_agent_decisions_agent_run_id'), 'agent_decisions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_created_at'), 'agent_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_decisions_portfolio_id'), 'agent_decisions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_proposal_id'), 'agent_decisions', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_symbol'), 'agent_decisions', ['symbol'], unique=False)
    op.create_index('ix_agent_decisions_symbol_created', 'agent_decisions', ['symbol', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('broker_account_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside', native_enum=False), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'VALIDATED', 'SUBMITTED', 'ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'FAILED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=True),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_orders_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_orders_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_orders_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_broker_account_id'), 'orders', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index('ix_orders_portfolio_status', 'orders', ['portfolio_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_proposal_id'), 'orders', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_positions_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_positions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_positions_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_positions_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_asset_id'), 'positions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_positions_created_at'), 'positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_positions_is_open'), 'positions', ['is_open'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index('ix_positions_portfolio_symbol_open', 'positions', ['portfolio_id', 'symbol', 'is_open'], unique=False)
    op.create_index(op.f('ix_positions_proposal_id'), 'positions', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_positions_strategy_id'), 'positions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('risk_evaluations',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'APPROVED_WITH_WARNINGS', 'REJECTED', name='riskdecision', native_enum=False), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('approved_quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('approved_position_percentage', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('settings_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('evaluated_by', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_risk_evaluations_proposal_id_trade_proposals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_evaluations'))
    )
    op.create_index(op.f('ix_risk_evaluations_created_at'), 'risk_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_evaluations_decision'), 'risk_evaluations', ['decision'], unique=False)
    op.create_index(op.f('ix_risk_evaluations_proposal_id'), 'risk_evaluations', ['proposal_id'], unique=False)
    op.create_table('executions',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('commission', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('broker_execution_id', sa.String(length=128), nullable=True),
    sa.Column('liquidity', sa.String(length=32), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_executions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_broker_execution_id'), 'executions', ['broker_execution_id'], unique=False)
    op.create_index(op.f('ix_executions_created_at'), 'executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_executions_order_id'), 'executions', ['order_id'], unique=False)
    op.create_table('trades',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('return_pct', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_trades_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_trades_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_trades_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trades_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index('ix_trades_portfolio_closed', 'trades', ['portfolio_id', 'closed_at'], unique=False)
    op.create_index(op.f('ix_trades_portfolio_id'), 'trades', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_trades_proposal_id'), 'trades', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_proposal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_portfolio_id'), table_name='trades')
    op.drop_index('ix_trades_portfolio_closed', table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_executions_order_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_created_at'), table_name='executions')
    op.drop_index(op.f('ix_executions_broker_execution_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_risk_evaluations_proposal_id'), table_name='risk_evaluations')
    op.drop_index(op.f('ix_risk_evaluations_decision'), table_name='risk_evaluations')
    op.drop_index(op.f('ix_risk_evaluations_created_at'), table_name='risk_evaluations')
    op.drop_table('risk_evaluations')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_strategy_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_proposal_id'), table_name='positions')
    op.drop_index('ix_positions_portfolio_symbol_open', table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_open'), table_name='positions')
    op.drop_index(op.f('ix_positions_created_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_asset_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_proposal_id'), table_name='orders')
    op.drop_index('ix_orders_portfolio_status', table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_agent_decisions_symbol_created', table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_symbol'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_proposal_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_portfolio_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_created_at'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_agent_run_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index(op.f('ix_trade_proposals_symbol'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_strategy_id'), table_name='trade_proposals')
    op.drop_index('ix_trade_proposals_status_created', table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_status'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_portfolio_id'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_created_at'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_agent_run_id'), table_name='trade_proposals')
    op.drop_table('trade_proposals')
    op.drop_index(op.f('ix_risk_snapshots_snapshot_time'), table_name='risk_snapshots')
    op.drop_index('ix_risk_snapshots_portfolio_time', table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_portfolio_id'), table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_created_at'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_time'), table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_portfolio_time', table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_created_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_symbol'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_created_at'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_asset_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_created_at'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_broker_account_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_backtest_results_created_at'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_backtest_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_created_at'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_strategy_signals_symbol_signal_time', table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_symbol'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_strategy_id'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_time'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_created_at'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_external_account_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_created_at'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_created_at'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_system_events_type_occurred', table_name='system_events')
    op.drop_index(op.f('ix_system_events_source'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_occurred_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_correlation_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_strategies_slug'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_created_at'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_market_quotes_symbol_quote_time', table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_symbol'), table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_quote_time'), table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_created_at'), table_name='market_quotes')
    op.drop_table('market_quotes')
    op.drop_index(op.f('ix_market_candles_symbol'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_created_at'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_candle_time'), table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_sector'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
